In [1]:
 import tensorflow as tf

In [ ]:
shuffle=tf.constant([[1,2],[3,4],[5,6]])
shuffle

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(shuffle,seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>

In [ ]:
# tensor of ones
tf.ones([4,6])

<tf.Tensor: shape=(4, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# tensor of zeros
tf.zeros([3,6])
# both are same
tf.zeros(shape=(3,6))

<tf.Tensor: shape=(3, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
#turn numpy to tensors
import numpy as np
# store_array=np.arrange(1,25,dtype=np.int32)
# store_array

numpy_A=np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
a=tf.constant(numpy_A)
a

<tf.Tensor: shape=(24,), dtype=int32, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)>

In [ ]:
numpy_A.shape

(24,)

In [ ]:
b=tf.constant(numpy_A,shape=(4,3,2))
b

<tf.Tensor: shape=(4, 3, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]], dtype=int32)>

In [ ]:
b.ndim

3

In [ ]:
store_value=tf.zeros(shape=(2,2,3,4))
store_value.shape
tf.size(store_value).numpy()
# store_value.ndim

48

**Tensors can run faster on the gpu as compare to the numpy **

In [ ]:
# get the each index of the dimention except the final one
dimention=tf.random.Generator.from_seed(32)
dimention=dimention.normal(shape=(3,3))
dimention

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.7901182 ,  1.585549  ,  0.4356279 ],
       [ 0.2364518 , -0.1589871 ,  1.302304  ],
       [ 0.9592239 ,  0.85874265, -1.5181769 ]], dtype=float32)>

In [ ]:
dimention[:2,:1]
dimention.shape

TensorShape([3, 3])

In [ ]:
storage_place=dimention[...,tf.newaxis]
# or
store2=dimention[:,:,tf.newaxis]
#or
store3=tf.expand_dims(dimention,axis=-1) #axis=0 will put the dimention in the start
store3.shape

TensorShape([3, 3, 1])

***You can add the values in the tensor using the addition operator***

In [ ]:
tensort=tf.constant([[1,2],[4,5]])
tensort+10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [14, 15]], dtype=int32)>

In [ ]:
tensort-10
tensort*10
# can also use the tensor flow built in functions too..
tf.multiply(tensort,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [40, 50]], dtype=int32)>

**Matrix multiplication**:
 " In machine learning, matrix multiplication is one of the most common tensor"

In [ ]:
matrix_mul=tf.constant([[1,2],[3,4]])
tf.matmul(matrix_mul,matrix_mul)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 10],
       [15, 22]], dtype=int32)>

In [ ]:
 matrix_mul*matrix_mulf

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 16]], dtype=int32)>

In [31]:
tensor_1=tf.constant([[1,2,3],[5,6,7]]);
tensor_2=tf.constant([[3],[7],[8]]);
tensor_2.shape
tf.matmul(tensor_1,tensor_2)
#   ----                THIS WILL NOT WORK BECAUSE FIRST MATRIX ROW SHOULD BE EQUAL TO THE SECOND MATRIX COLUMN
# tf.matmul(tensor_2,tensor_1)  # TO MAKE THIS STAEMENT WORK
# tensor_1.shape,tensor_2.shape
reshape_tensor2=tf.reshape(tensor_2,shape=(1,3))
reshape_tensor1=tf.reshape(tensor_1,shape=(3,2))
reshape_tensor2.shape,reshape_tensor1.shape
tf.matmul(reshape_tensor2,reshape_tensor1)

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[72, 97]], dtype=int32)>

In [34]:
tf.transpose(tensor_1).shape

TensorShape([3, 2])