In [2]:
import tensorflow as tf
print(tf.__version__)

2.17.0


In [7]:
change=tf.Variable([[11,2],[3,4]])

change
change[0].assign(120)

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[120, 120],
       [  3,   4]], dtype=int32)>

In [10]:
#random tensor create
rand_tensor=tf.random.Generator.from_seed(42)
rand_tensor=rand_tensor.normal(shape=(3,2))
rand_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [11]:
rand2=tf.random.Generator.from_seed(42)
rand2=rand2.normal(shape=(3,2))
rand_tensor==rand2
# s

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [4]:
scaler=tf.constant(7)
scaler.ndim

0

In [ ]:
vector=tf.constant([0,23],dtype=tf.float32)
# vector.
vector

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 0., 23.], dtype=float32)>

In [ ]:
tensor=tf.constant([[[1,2,3],[5,6,7]],[[1,2,3],[5,6,7]],[[1,2,3],[5,6,7]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [5, 6, 7]],

       [[1, 2, 3],
        [5, 6, 7]],

       [[1, 2, 3],
        [5, 6, 7]]], dtype=int32)>