In [33]:
import tensorflow as tf
import numpy as np

In [ ]:
const_1=tf.constant([1,2,3,4])
const_float=tf.constant([.1,.2,.4])
const_float

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.1, 0.2, 0.4], dtype=float32)>

In [ ]:
const_1.dtype

tf.int32

**CHANGE FROM FLOAT 32 TO FLOAT 16**

In [ ]:
chan_const1=tf.cast(const_1,dtype=tf.float16)
chan_const1

<tf.Tensor: shape=(4,), dtype=float16, numpy=array([1., 2., 3., 4.], dtype=float16)>

In [ ]:
#find the mimum, max, mean, sum if the tensor
rand_values=tf.constant(np.random.randint(0,100,size=50))
rand_values

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([85, 96, 87, 87, 67, 23, 85, 22, 60, 78, 28, 57, 67, 82, 48, 85, 44,
       91, 86, 11, 64, 86, 53, 38, 37, 78, 81, 25, 94,  3, 22, 28,  2, 90,
       97, 25, 55, 80, 11, 43, 48, 11, 59, 55, 63,  4, 54, 81, 35, 72])>

In [ ]:
tf.size(rand_values)

<tf.Tensor: shape=(), dtype=int32, numpy=50>

In [ ]:
rand_values.shape

TensorShape([50])

In [ ]:
rand_values.ndim

1

In [ ]:
#find the minimum value
tf.reduce_min(rand_values)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [ ]:
#find the maximum values
tf.reduce_max(rand_values)

<tf.Tensor: shape=(), dtype=int64, numpy=97>

In [ ]:
tf.reduce_mean(rand_values)

<tf.Tensor: shape=(), dtype=int64, numpy=55>

In [ ]:
tf.reduce_sum(rand_values)

<tf.Tensor: shape=(), dtype=int64, numpy=2783>

In [ ]:
#for variance first convert these values to the float
floated_value=tf.cast(rand_values,dtype=tf.float32)
tf.math.reduce_variance(floated_value)
# floated_value

<tf.Tensor: shape=(), dtype=float32, numpy=808.5845>

In [ ]:
#now find the standard deviation of
tf.math.reduce_std(floated_value)

<tf.Tensor: shape=(), dtype=float32, numpy=28.43562>

In [ ]:
# tf.reduce_variance(rand_values)

***POSITIONAL MAXIMUM AND MINIMUM***

In [25]:
# create a new tensor for finding the positional min and max
tf.random.set_seed(42);
post_vec=tf.random.uniform(shape=[50]);

In [26]:
post_vec

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [27]:
# gives me the index of the maximum value in the array
tf.argmax(post_vec)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [30]:
# Now print the value
post_vec[tf.argmax(post_vec)]
# or way 2
tf.reduce_max(post_vec)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [42]:
#test
many_dim=tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,50))


In [43]:
many_dim.shape

TensorShape([1, 1, 1, 1, 50])

**SQUEEZE THE SHAPE OF THE MATRIX**

In [45]:
squeeze=tf.squeeze(many_dim)
squeeze.shape

TensorShape([50])

***ONE HOT ENCODING***

In [52]:
list=[0,1,2]
#one hot encode
tf.one_hot(list,depth=3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [53]:
#specify the custom values
tf.one_hot(list,depth=3,on_value="i love deep learning",off_value="i also dance")

<tf.Tensor: shape=(3, 3), dtype=string, numpy=
array([[b'i love deep learning', b'i also dance', b'i also dance'],
       [b'i also dance', b'i love deep learning', b'i also dance'],
       [b'i also dance', b'i also dance', b'i love deep learning']],
      dtype=object)>

**square root**

In [60]:
h=tf.range(1,9)
tf.square(h)
# int 32 cannot be used, convert to float32
tf.math.sqrt(tf.cast(h,dtype=tf.float32))
tf.math.log(tf.cast(h,dtype=tf.float32))

<tf.Tensor: shape=(8,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415], dtype=float32)>

**tensorflow and numpy**

In [64]:
#create a tensor from the numpy array
j=tf.constant(np.array([1.,2.,3.]))
#convert tensor back to numpy
np.array(j),type(np.array(j))

(array([1., 2., 3.]), numpy.ndarray)

In [66]:
#convert tesor j to numpy array
j.numpy(),type(j.numpy())

(array([1., 2., 3.]), numpy.ndarray)

In [67]:
another=tf.constant(np.array([1.,2.,23.]))
type(another)

tensorflow.python.framework.ops.EagerTensor