In [ ]:
import pandas as pd
import numpy as np
df=pd.DataFrame({
    "text": [
        "apple banana cherry",
        "dog cat dog",
        "sun moon stars",
        "car bike car",
        "python java python",
        "red blue green",
        "happy sad happy",
        "tree river tree",
        "school college school",
        "music art music"
    ],
    "output": [1, 1, 0, 0, 1, 0, 1, 1, 1, 1]
})
df

text  output
0    apple banana cherry       1
1            dog cat dog       1
2         sun moon stars       0
3           car bike car       0
4     python java python       1
5         red blue green       0
6        happy sad happy       1
7        tree river tree       1
8  school college school       1
9        music art music       1

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
# for the uni-gram
cv=CountVectorizer()

#bi-gram
cv2=CountVectorizer(ngram_range=(2,2))
# cv

In [ ]:
bow=cv.fit_transform(df["text"])
bow2=cv2.fit_transform(df["text"])
bow

<10x23 sparse matrix of type '<class 'numpy.int64'>'
	with 23 stored elements in Compressed Sparse Row format>

In [ ]:
# print the dictionary
print(cv2.vocabulary_)

{'apple banana': 0, 'banana cherry': 2, 'dog cat': 8, 'cat dog': 6, 'sun moon': 18, 'moon stars': 11, 'car bike': 5, 'bike car': 3, 'python java': 13, 'java python': 10, 'red blue': 14, 'blue green': 4, 'happy sad': 9, 'sad happy': 16, 'tree river': 19, 'river tree': 15, 'school college': 17, 'college school': 7, 'music art': 12, 'art music': 1}


In [ ]:
bow2[3].toarray()

array([[0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
cv.transform(["car bike car car"]).toarray()

array([[0, 0, 0, 1, 0, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0]])

In [ ]:
# TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer()
tfidf.fit_transform(df['text']).toarray()

array([[0.57735027, 0.        , 0.57735027, 0.        , 0.        ,
        0.        , 0.        , 0.57735027, 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.4472136 , 0.        , 0.        , 0.89442719,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.57735027, 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.57735027, 0.57735027, 0.        ],
       [0.        , 0.        , 0.        , 0.447

In [ ]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())


[2.70474809 2.70474809 2.70474809 2.70474809 2.70474809 2.70474809
 2.70474809 2.70474809 2.70474809 2.70474809 2.70474809 2.70474809
 2.70474809 2.70474809 2.70474809 2.70474809 2.70474809 2.70474809
 2.70474809 2.70474809 2.70474809 2.70474809 2.70474809]
['apple' 'art' 'banana' 'bike' 'blue' 'car' 'cat' 'cherry' 'college' 'dog'
 'green' 'happy' 'java' 'moon' 'music' 'python' 'red' 'river' 'sad'
 'school' 'stars' 'sun' 'tree']


In [ ]:
tfidf.